import { GoogleGenAI } from "@google/genai";

export interface Env {
  GEMINI_API_KEY: string;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Only allow POST requests to /api/gemini
    if (request.method !== "POST" || url.pathname !== "/api/gemini") {
      return new Response("Not Found", { status: 404 });
    }

    try {
      const { action, payload } = await request.json() as any;
      const genAI = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

      if (action === "analyzeImage") {
        const response = await genAI.models.generateContent({
          model: "gemini-3-flash-preview",
          contents: [
            {
              role: "user",
              parts: [
                { text: payload.prompt },
                {
                  inlineData: {
                    mimeType: payload.mimeType,
                    data: payload.base64Data
                  }
                }
              ]
            }
          ],
          config: {
            responseMimeType: "application/json",
            responseSchema: {
              type: "OBJECT",
              properties: {
                imageDescription: { type: "STRING" },
                suggestions: {
                  type: "ARRAY",
                  items: {
                    type: "OBJECT",
                    properties: {
                      id: { type: "STRING" },
                      title: { type: "STRING" },
                      description: { type: "STRING" },
                      reasoning: { type: "STRING" },
                    },
                    required: ["id", "title", "description", "reasoning"],
                  },
                },
              },
              required: ["imageDescription", "suggestions"],
            }
          }
        });
        
        const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) throw new Error("No text generated by Gemini");

        return new Response(text, {
          headers: { "Content-Type": "application/json" },
        });
      }

      if (action === "generatePrompt") {
        const response = await genAI.models.generateContent({
          model: "gemini-3-flash-preview",
          contents: [{ role: "user", parts: [{ text: payload.prompt }] }]
        });
        
        const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) throw new Error("No text generated by Gemini");

        return new Response(JSON.stringify({ text }), {
          headers: { "Content-Type": "application/json" },
        });
      }

      if (action === "generateImage") {
        const parts: any[] = [{ text: payload.prompt }];
        if (payload.base64Data && payload.mimeType) {
          parts.push({
            inlineData: {
              mimeType: payload.mimeType,
              data: payload.base64Data
            }
          });
        }

        const response = await genAI.models.generateContent({
          model: "gemini-3-pro-image-preview",
          contents: [{ role: "user", parts }],
          config: {
            responseModalities: ["IMAGE"]
          }
        });

        const candidates = response.candidates;
        if (candidates && candidates[0] && candidates[0].content && candidates[0].content.parts) {
             for (const part of candidates[0].content.parts) {
                 if (part.inlineData) {
                     return new Response(JSON.stringify({ text: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}` }), {
                         headers: { "Content-Type": "application/json" },
                     });
                 }
             }
        }
        
        throw new Error("No image generated by Gemini");
      }

      return new Response("Invalid Action", { status: 400 });
    } catch (error: any) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
