import { GoogleGenAI } from "@google/genai";

export interface Env {
  GEMINI_API_KEY: string;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Only allow POST requests to /api/gemini
    if (request.method !== "POST" || url.pathname !== "/api/gemini") {
      return new Response("Not Found", { status: 404 });
    }

    try {
      const { action, payload } = await request.json() as any;
      const genAI = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

      if (action === "analyzeImage") {
        const model = genAI.getGenerativeModel({
          model: "gemini-3-flash-preview",
          generationConfig: {
            responseMimeType: "application/json",
            // @ts-ignore
            responseSchema: {
              type: "object",
              properties: {
                imageDescription: { type: "string" },
                suggestions: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      id: { type: "string" },
                      title: { type: "string" },
                      description: { type: "string" },
                      reasoning: { type: "string" },
                    },
                    required: ["id", "title", "description", "reasoning"],
                  },
                },
              },
              required: ["imageDescription", "suggestions"],
            }
          }
        });
        
        const result = await model.generateContent([
          {
            inlineData: {
              data: payload.base64Data,
              mimeType: payload.mimeType,
            },
          },
          { text: payload.prompt },
        ]);
        
        return new Response(result.response.text(), {
          headers: { "Content-Type": "application/json" },
        });
      }

      if (action === "generatePrompt") {
        const model = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });
        const result = await model.generateContent(payload.prompt);
        return new Response(JSON.stringify({ text: result.response.text() }), {
          headers: { "Content-Type": "application/json" },
        });
      }

      if (action === "generateImage") {
        const model = genAI.getGenerativeModel({
          model: "nano-banana-pro"
        });
        
        const contents = [{ text: payload.prompt }];
        if (payload.base64Data && payload.mimeType) {
          contents.unshift({
            inlineData: { data: payload.base64Data, mimeType: payload.mimeType }
          } as any);
        }

        const result = await model.generateContent({
          contents,
          generationConfig: {
            // @ts-ignore
            imageConfig: { aspectRatio: "1:1", imageSize: "1K" }
          }
        });
        const response = await result.response;
        
        for (const part of response.candidates?.[0]?.content?.parts || []) {
          if (part.inlineData) {
            return new Response(JSON.stringify({ text: `data:image/png;base64,${part.inlineData.data}` }), {
              headers: { "Content-Type": "application/json" },
            });
          }
        }
        throw new Error("No image generated by Gemini");
      }

      return new Response("Invalid Action", { status: 400 });
    } catch (error: any) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
